In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [9]:
dataset = pd.read_csv('atlanta_9-24-2016_9-30-2017.csv')
dataset['Average Price']=((dataset['Low Price']+dataset['High Price'])/2)
dataset=dataset.drop(columns=[ 'Commodity Name','City Name','Type','Sub Variety','Grade','Date','Low Price','High Price','Mostly Low','Mostly High','Origin District','Color','Environment','Unit of Sale','Quality','Condition','Appearance','Storage','Crop','Repack','Trans Mode'])
dataset=dataset.dropna(how='any')
y=dataset.iloc[:,-1].values
X=dataset.iloc[:,:-1].values

In [10]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X[:,0]=le.fit_transform(X[:,0])
X[:,1]=le.fit_transform(X[:,1])
X[:,2]=le.fit_transform(X[:,2])
X[:,3]=le.fit_transform(X[:,3])
print(X)

[[1 0 2 0]
 [1 0 2 5]
 [1 0 2 3]
 [1 0 2 4]
 [1 0 2 0]
 [1 0 2 5]
 [1 0 2 3]
 [1 0 2 4]
 [1 0 2 0]
 [1 0 2 5]
 [1 0 2 3]
 [1 0 2 4]
 [1 0 0 2]
 [1 0 2 0]
 [1 0 2 5]
 [1 0 2 3]
 [1 0 2 4]
 [1 0 0 2]
 [1 0 2 0]
 [1 0 2 5]
 [1 0 2 3]
 [1 0 2 4]
 [1 0 0 2]
 [1 0 2 0]
 [1 0 2 5]
 [1 0 2 3]
 [1 0 2 4]
 [1 0 0 2]
 [1 0 2 0]
 [1 0 2 5]
 [1 0 2 3]
 [1 0 2 4]
 [2 0 1 2]
 [2 0 2 1]
 [2 0 4 1]
 [0 1 2 4]
 [0 1 2 4]
 [0 1 2 4]
 [0 1 2 4]
 [1 1 3 4]
 [1 1 3 4]
 [1 1 3 4]
 [1 1 3 4]
 [1 1 3 4]
 [1 1 3 4]
 [1 1 3 4]
 [1 1 3 4]
 [1 1 3 4]
 [1 1 3 4]
 [2 1 2 4]
 [2 1 2 4]
 [2 1 2 4]
 [2 1 2 4]
 [2 1 2 4]
 [2 1 2 4]
 [2 1 2 4]]


In [11]:
print(y)

[147.375 149.875 152.375 150.    147.375 149.875 152.375 150.    147.375
 149.875 152.375 150.    142.5   147.375 149.875 152.375 150.    142.5
 147.375 149.875 152.375 150.    142.5   147.375 149.875 152.375 150.
 142.5   147.375 149.875 152.375 150.    150.    142.5   140.     14.75
  14.75   14.75   14.75  135.    135.    135.    135.    135.    135.
 129.25  129.25  129.25  129.25  248.    248.    248.    248.    248.
 248.    248.   ]


In [12]:
y=y.reshape(len(y),1)
print(y)

[[147.375]
 [149.875]
 [152.375]
 [150.   ]
 [147.375]
 [149.875]
 [152.375]
 [150.   ]
 [147.375]
 [149.875]
 [152.375]
 [150.   ]
 [142.5  ]
 [147.375]
 [149.875]
 [152.375]
 [150.   ]
 [142.5  ]
 [147.375]
 [149.875]
 [152.375]
 [150.   ]
 [142.5  ]
 [147.375]
 [149.875]
 [152.375]
 [150.   ]
 [142.5  ]
 [147.375]
 [149.875]
 [152.375]
 [150.   ]
 [150.   ]
 [142.5  ]
 [140.   ]
 [ 14.75 ]
 [ 14.75 ]
 [ 14.75 ]
 [ 14.75 ]
 [135.   ]
 [135.   ]
 [135.   ]
 [135.   ]
 [135.   ]
 [135.   ]
 [129.25 ]
 [129.25 ]
 [129.25 ]
 [129.25 ]
 [248.   ]
 [248.   ]
 [248.   ]
 [248.   ]
 [248.   ]
 [248.   ]
 [248.   ]]


In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [14]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
poly_reg = PolynomialFeatures(degree = 9)
X_train = poly_reg.fit_transform(X_train)
X_test = poly_reg.fit_transform(X_test)
lin_reg_2 = LinearRegression()
lin_reg_2.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [15]:
y_pred =lin_reg_2.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[132.7  135.  ]
 [152.38 152.38]
 [132.7  129.25]
 [149.87 149.88]
 [145.51 150.  ]
 [147.3  142.5 ]
 [ 14.75  14.75]
 [132.7  135.  ]
 [248.   248.  ]
 [132.7  135.  ]
 [132.7  129.25]
 [150.   150.  ]]


Note: this is one way of implmenting the algorithm based on the size and other features now let us try the reverse method  and see if it performs as expected

In [ ]:
dataset = pd.read_csv('atlanta_9-24-2016_9-30-2017.csv')
dataset['Average Price']=((dataset['Low Price']+dataset['High Price'])/2)
dataset['Size']=dataset['Item Size']#making anew column size as the last column so that preprocessing would be easy
dataset=dataset.drop(columns=[ 'Item Size','Commodity Name','City Name','Type','Sub Variety','Grade','Date','Low Price','High Price','Mostly Low','Mostly High','Origin District','Color','Environment','Unit of Sale','Quality','Condition','Appearance','Storage','Crop','Repack','Trans Mode'])
dataset=dataset.dropna(how='any')
X=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values


In [27]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X[:,0]=le.fit_transform(X[:,0])
X[:,1]=le.fit_transform(X[:,1])
X[:,2]=le.fit_transform(X[:,2])
y=le.fit_transform(y)
print(X)

[[1 0 2 147.375]
 [1 0 2 149.875]
 [1 0 2 152.375]
 [1 0 2 150.0]
 [1 0 2 147.375]
 [1 0 2 149.875]
 [1 0 2 152.375]
 [1 0 2 150.0]
 [1 0 2 147.375]
 [1 0 2 149.875]
 [1 0 2 152.375]
 [1 0 2 150.0]
 [1 0 0 142.5]
 [1 0 2 147.375]
 [1 0 2 149.875]
 [1 0 2 152.375]
 [1 0 2 150.0]
 [1 0 0 142.5]
 [1 0 2 147.375]
 [1 0 2 149.875]
 [1 0 2 152.375]
 [1 0 2 150.0]
 [1 0 0 142.5]
 [1 0 2 147.375]
 [1 0 2 149.875]
 [1 0 2 152.375]
 [1 0 2 150.0]
 [1 0 0 142.5]
 [1 0 2 147.375]
 [1 0 2 149.875]
 [1 0 2 152.375]
 [1 0 2 150.0]
 [2 0 1 150.0]
 [2 0 2 142.5]
 [2 0 4 140.0]
 [0 1 2 14.75]
 [0 1 2 14.75]
 [0 1 2 14.75]
 [0 1 2 14.75]
 [1 1 3 135.0]
 [1 1 3 135.0]
 [1 1 3 135.0]
 [1 1 3 135.0]
 [1 1 3 135.0]
 [1 1 3 135.0]
 [1 1 3 129.25]
 [1 1 3 129.25]
 [1 1 3 129.25]
 [1 1 3 129.25]
 [2 1 2 248.0]
 [2 1 2 248.0]
 [2 1 2 248.0]
 [2 1 2 248.0]
 [2 1 2 248.0]
 [2 1 2 248.0]
 [2 1 2 248.0]]


In [28]:
print(y)

[0 5 3 4 0 5 3 4 0 5 3 4 2 0 5 3 4 2 0 5 3 4 2 0 5 3 4 2 0 5 3 4 2 1 1 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4]


In [29]:
y=y.reshape(len(y),1)
print(y)

[[0]
 [5]
 [3]
 [4]
 [0]
 [5]
 [3]
 [4]
 [0]
 [5]
 [3]
 [4]
 [2]
 [0]
 [5]
 [3]
 [4]
 [2]
 [0]
 [5]
 [3]
 [4]
 [2]
 [0]
 [5]
 [3]
 [4]
 [2]
 [0]
 [5]
 [3]
 [4]
 [2]
 [1]
 [1]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]]


In [30]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [31]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
poly_reg = PolynomialFeatures(degree = 9)
X_train = poly_reg.fit_transform(X_train)
X_test = poly_reg.fit_transform(X_test)
lin_reg_2 = LinearRegression()
lin_reg_2.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [32]:
y_pred =lin_reg_2.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[4.00e+00 4.00e+00]
 [3.00e+00 3.00e+00]
 [4.00e+00 4.00e+00]
 [5.00e+00 5.00e+00]
 [2.09e+06 2.00e+00]
 [1.88e+06 1.00e+00]
 [4.00e+00 4.00e+00]
 [4.00e+00 4.00e+00]
 [4.00e+00 4.00e+00]
 [4.00e+00 4.00e+00]
 [4.00e+00 4.00e+00]
 [4.00e+00 4.00e+00]]
